apiVersion: v1
kind: Service
metadata:
    namespace: mongo-namespace
    name: mongo-service
spec:
#if type is not defined then it is cludterip
    selector:
        app: mongo
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
