apiVersion: v1
kind: Service
metadata:
  namespace: mongo-namespace
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      #if you dont want to use nodeport then also it will deploy the service on loadbalancer, nodeport if if you want specific port to expose that service
      nodePort: 30000
