apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: mongo-namespace
    name: mongo-deployment
    labels:
        app: mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mongo
    template:
        metadata:
            labels:
                app: mongo
        spec:
            containers:
            - name: mongo
              image: mongo
              ports:
              - containerPort: 27017
              env:
              # reference to secret.yaml keys/values
              - name: MONGO_INITDB_ROOT_USERNAME
                valueFrom:
                    secretKeyRef:
                        name: mongo-secret
                        key: mongo-root-username
              - name: MONGO_INITDB_ROOT_PASSWORD
                valueFrom:
                    secretKeyRef:
                        name: mongo-secret
                        key: mongo-root-password
